name: Check Secret Variable

on: [push]

jobs:
  check_variables:
    runs-on: ubuntu-latest

    steps:
    - name: Check if AZURE_STORAGE_SAS_TOKEN is set
      env:
        AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
      run: |
        if [ -z "$AZURE_STORAGE_SAS_TOKEN" ]; then
          echo "AZURE_STORAGE_SAS_TOKEN secret is not set"
          exit 1
        else
          echo "AZURE_STORAGE_SAS_TOKEN secret is set"
        fi
