name: Check Secret Variable

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check_variables:
    runs-on: ubuntu-latest

    steps:
    - name: Check if AZURE_STORAGE_SAS_TOKEN is set
      env:
        committer: ${{ github.event.pull_request.head.user.login }}
        author: ${{ github.event.pull_request.user.login }}
      run: |
        echo "Committer: $committer"
        echo "Author of the pull request: $author"
         echo "pusher: ${{ github.actor }}"
