name: Check Secret Variable

on: [push]

jobs:
  check_variables:
    runs-on: ubuntu-latest

    steps:
    - name: Check if AZURE_STORAGE_SAS_TOKEN is set
     # env:
      #  AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
      run: |
        chandra=${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
        echo $chandra

